### ISSUE TITLE
Update `simulation`-related objects and queries

### ISSUE THREAD

**Issue by cartermak** [NASA-AMMOS/aerie-cli#10]
See [upgrade guide](https://nasa-ammos.github.io/aerie-docs/upgrade-guides/1-3-0-to-1-4-0/#temporal-subset-simulation-725) for context. I expect, at a minimum, that the scheduling spec will need to be removed from `AerieClient.create_activity_plan()`; it's likely necessary to update `AerieClient.simulate_plan()` and the associated command, as well, to support temporal subset simulation.

**Comment by mattdailis** [comment]
> the scheduling spec will need to be removed

Slight amendment - I think the scheduling spec should stay, but the `insert_simulation_one` is now being done by a trigger on plan insert, so I think it will need to be removed, and perhaps replaced by an "update" of the auto-created record:

https://github.com/NASA-AMMOS/aerie-cli/blob/c4c4c6de472acd4ca83c864aebe70d8e92a4ec43/src/aerie_cli/aerie_client.py#L183-L189

**Comment by cartermak** [comment]
Turns out `simulate_plan` is fine. We can probably remove the plan boundary update in the future, but the 1.4.0 backward-compatibility is good for now.
