### ISSUE TITLE
Update for Aerie 2.8.0

### ISSUE THREAD

**Issue by parkerabercrombie** [NASA-AMMOS/aerie-cli#132]
Update CLI to support Aerie 2.8.0. In particular, `createSchedulingSpecification` has been removed (the database now handles this).

Upgrade guide: https://nasa-ammos.github.io/aerie-docs/upgrade-guides/2-7-1-to-2-8-0/

**Comment by joshhaug** [comment]
Relevant PR on Aerie CLI: https://github.com/NASA-AMMOS/aerie-cli/pull/133

**Comment by cartermak** [comment]
Closed by #133
