### ISSUE TITLE
Upcoming Aerie Gateway release will rename ssoToken to token

### ISSUE THREAD

**Issue by Mythicaeda** [NASA-AMMOS/aerie-cli#17]
[Aerie Gateway 1.7.0 will replace ssotoken with token](https://github.com/NASA-AMMOS/aerie-gateway/pull/23/files#diff-c1d24f37e431ed76b5a58bc45a105c8ddbc9f41fd4076fc3f37e862d58d548cbR96-R101). [Currently, the `ssotoken` key is hardcoded into the Auth.Native](https://github.com/NASA-AMMOS/aerie-cli/blob/main/src/aerie_cli/aerie_host.py#LL196C71-L196C71). This needs to be either updated or placed in an if-else.

**Comment by cartermak** [comment]
Addressed by #24
