### ISSUE TITLE
Updates to scheduling commands

### ISSUE THREAD

**Issue by meganmjones** [NASA-AMMOS/aerie-cli#19]
Currently, the scheduling command allows upload of a text file with one path on each line to a scheduling rule file, in decreasing priority order. However, several fixes/additions can be made to improve this command for future use, including:

- Fixing the scheduling upload command as it currently takes in --scheduling-name which is a single name that ties to all goals entered from the text file. Ideally, the user could enter a list of names to associate to the listed goals in the text file or have the option for uploaded goals to match the .ts file's naming convention.
- Ability for upload to see what goals of certain name already exist in selected model/plan and confirm with user if they'd like to overwrite old goal or not. Given this command will likely be run after a set of goals have previously been uploaded, this feature could help avoid overwriting goals (or giving an error that the goal name already exists)

**Comment by colin-lewis-19** [comment]
The first idea presented here will be a huge quality of life improvement
