### ISSUE TITLE
Build Tests with Aerie "BananaNation" mission model

### ISSUE THREAD

**Issue by cartermak** [NASA-AMMOS/aerie-cli#20]
Update query unit tests to reference the Banananation mission model in a way that we can automatically generate updated test case files (with manual review, of course). This will make it easier to update unit test cases.

**Comment by ewferg** [comment]
I'd love if we use a different mission model for testing that is more domain specific (example s/c mission model), but I am not sure if there is a better one than Banananation right now.

**Comment by cartermak** [comment]
That's fair. I'm mainly concerned with properly handling all of the activity/plan/simulation properties (e.g., anchoring, simulation start/end times), so my opinion is that we just need a model and test cases that adequately exercise Aerie's features.

**Comment by cartermak** [comment]
Addressed by #54
