### ISSUE TITLE
Add support for activity directive metadata schemas

### ISSUE THREAD

**Issue by parkerabercrombie** [NASA-AMMOS/aerie-cli#37]
Aerie allows the mission to define custom metadata schema for activity directives. The aerie-cli should allow a user to manage these schemas.

As a first cut, I think we'd want to support basic list/create/delete features:
```
aerie-cli metadata list
aerie-cli metadata upload <schema.json>
aerie-cli metadata delete <name>
```

Where the content of `schema.json` is a list of metadata schemas like in this example: https://nasa-ammos.github.io/aerie-docs/planning/activity-directive-metadata/#query-variable

**Comment by cartermak** [comment]
Addressed by #40
