### ISSUE TITLE
Integration Test Updates

### ISSUE THREAD

**Issue by cartermak** [NASA-AMMOS/aerie-cli#62]
Improvements to build on #54:

- Pull a version-specific build of the `banananation` JAR file from [here](https://github.com/NASA-AMMOS/aerie/packages/1171106/versions)
- Pull (or otherwise store locally) a docker-compose for each Aerie version under test
- Add a matrix of Aerie versions to test

**Comment by Navarro-Jonathan** [comment]
One possible change is to remove the secrets from the workflow. The workflow's secret's values could be set to anything, so those values could be hardcoded. This would potentially make debugging easier if any authentication errors come up.

Relevant discussion: https://github.com/NASA-AMMOS/aerie-cli/pull/54#discussion_r1277803415

**Comment by cartermak** [comment]
Mostly addressed by #88 . This doesn't automatically pull the banananation Jar, but instead we store the JARs for all compatible Aerie versions.
