### ISSUE TITLE
Fix Tags

### ISSUE THREAD

**Issue by Mythicaeda** [NASA-AMMOS/aerie-cli#65]
Tags are gone from activity_directive. They should be available as an array still in the `activity_directive_extended` view
There is a tags table now, as well as join tables with plan, activity directive, and some scheduling/sequencing tables.

**Comment by cartermak** [comment]
De-scoping from v2 as I've removed tags support for now, but keeping the issue open for reconsideration in the future.

**Comment by cartermak** [comment]
Addressed by #108 , #117 , and #119
